package me.itangqi.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.itangqi.greendao.DBChat;
import me.itangqi.greendao.DBMessage;
import me.itangqi.greendao.DBFriend;

import me.itangqi.greendao.DBChatDao;
import me.itangqi.greendao.DBMessageDao;
import me.itangqi.greendao.DBFriendDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBChatDaoConfig;
    private final DaoConfig dBMessageDaoConfig;
    private final DaoConfig dBFriendDaoConfig;

    private final DBChatDao dBChatDao;
    private final DBMessageDao dBMessageDao;
    private final DBFriendDao dBFriendDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBChatDaoConfig = daoConfigMap.get(DBChatDao.class).clone();
        dBChatDaoConfig.initIdentityScope(type);

        dBMessageDaoConfig = daoConfigMap.get(DBMessageDao.class).clone();
        dBMessageDaoConfig.initIdentityScope(type);

        dBFriendDaoConfig = daoConfigMap.get(DBFriendDao.class).clone();
        dBFriendDaoConfig.initIdentityScope(type);

        dBChatDao = new DBChatDao(dBChatDaoConfig, this);
        dBMessageDao = new DBMessageDao(dBMessageDaoConfig, this);
        dBFriendDao = new DBFriendDao(dBFriendDaoConfig, this);

        registerDao(DBChat.class, dBChatDao);
        registerDao(DBMessage.class, dBMessageDao);
        registerDao(DBFriend.class, dBFriendDao);
    }
    
    public void clear() {
        dBChatDaoConfig.getIdentityScope().clear();
        dBMessageDaoConfig.getIdentityScope().clear();
        dBFriendDaoConfig.getIdentityScope().clear();
    }

    public DBChatDao getDBChatDao() {
        return dBChatDao;
    }

    public DBMessageDao getDBMessageDao() {
        return dBMessageDao;
    }

    public DBFriendDao getDBFriendDao() {
        return dBFriendDao;
    }

}
