package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBCHAT".
 */
public class DBChat {

    private Long id;
    /** Not-null value. */
    private String my_userId;
    /** Not-null value. */
    private String channalId;
    /** Not-null value. */
    private String friend_userId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String message;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String imgUrl;
    /** Not-null value. */
    private String unReadNum;

    public DBChat() {
    }

    public DBChat(Long id) {
        this.id = id;
    }

    public DBChat(Long id, String my_userId, String channalId, String friend_userId, String name, String message, String date, String imgUrl, String unReadNum) {
        this.id = id;
        this.my_userId = my_userId;
        this.channalId = channalId;
        this.friend_userId = friend_userId;
        this.name = name;
        this.message = message;
        this.date = date;
        this.imgUrl = imgUrl;
        this.unReadNum = unReadNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMy_userId() {
        return my_userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMy_userId(String my_userId) {
        this.my_userId = my_userId;
    }

    /** Not-null value. */
    public String getChannalId() {
        return channalId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChannalId(String channalId) {
        this.channalId = channalId;
    }

    /** Not-null value. */
    public String getFriend_userId() {
        return friend_userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFriend_userId(String friend_userId) {
        this.friend_userId = friend_userId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getMessage() {
        return message;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMessage(String message) {
        this.message = message;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getImgUrl() {
        return imgUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /** Not-null value. */
    public String getUnReadNum() {
        return unReadNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUnReadNum(String unReadNum) {
        this.unReadNum = unReadNum;
    }

}
