package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBCHAT".
 */
public class DBChat {

    private Long id;
    /** Not-null value. */
    private String channelId;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String message;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String imgUrl;

    public DBChat() {
    }

    public DBChat(Long id) {
        this.id = id;
    }

    public DBChat(Long id, String channelId, String userId, String name, String message, String date, String imgUrl) {
        this.id = id;
        this.channelId = channelId;
        this.userId = userId;
        this.name = name;
        this.message = message;
        this.date = date;
        this.imgUrl = imgUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getChannelId() {
        return channelId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getMessage() {
        return message;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMessage(String message) {
        this.message = message;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getImgUrl() {
        return imgUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}
