package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBFRIEND".
 */
public class DBFriend {

    private Long id;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String imgUrl;
    /** Not-null value. */
    private String phone;
    /** Not-null value. */
    private String address;

    public DBFriend() {
    }

    public DBFriend(Long id) {
        this.id = id;
    }

    public DBFriend(Long id, String userId, String name, String imgUrl, String phone, String address) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.imgUrl = imgUrl;
        this.phone = phone;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getImgUrl() {
        return imgUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

}
