package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBMESSAGE".
 */
public class DBMessage {

    private Long id;
    /** Not-null value. */
    private String my_userId;
    /** Not-null value. */
    private String message;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String fromId;
    /** Not-null value. */
    private String toId;
    /** Not-null value. */
    private String channelId;
    /** Not-null value. */
    private String image;
    /** Not-null value. */
    private String from_name;
    /** Not-null value. */
    private String channal_name;
    private boolean from_me;
    private boolean is_sended;

    public DBMessage() {
    }

    public DBMessage(Long id) {
        this.id = id;
    }

    public DBMessage(Long id, String my_userId, String message, String date, String fromId, String toId, String channelId, String image, String from_name, String channal_name, boolean from_me, boolean is_sended) {
        this.id = id;
        this.my_userId = my_userId;
        this.message = message;
        this.date = date;
        this.fromId = fromId;
        this.toId = toId;
        this.channelId = channelId;
        this.image = image;
        this.from_name = from_name;
        this.channal_name = channal_name;
        this.from_me = from_me;
        this.is_sended = is_sended;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMy_userId() {
        return my_userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMy_userId(String my_userId) {
        this.my_userId = my_userId;
    }

    /** Not-null value. */
    public String getMessage() {
        return message;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMessage(String message) {
        this.message = message;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getFromId() {
        return fromId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /** Not-null value. */
    public String getToId() {
        return toId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToId(String toId) {
        this.toId = toId;
    }

    /** Not-null value. */
    public String getChannelId() {
        return channelId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /** Not-null value. */
    public String getImage() {
        return image;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImage(String image) {
        this.image = image;
    }

    /** Not-null value. */
    public String getFrom_name() {
        return from_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom_name(String from_name) {
        this.from_name = from_name;
    }

    /** Not-null value. */
    public String getChannal_name() {
        return channal_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChannal_name(String channal_name) {
        this.channal_name = channal_name;
    }

    public boolean getFrom_me() {
        return from_me;
    }

    public void setFrom_me(boolean from_me) {
        this.from_me = from_me;
    }

    public boolean getIs_sended() {
        return is_sended;
    }

    public void setIs_sended(boolean is_sended) {
        this.is_sended = is_sended;
    }

}
