package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBMESSAGE".
 */
public class DBMessage {

    private Long id;
    /** Not-null value. */
    private String message;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String fromId;
    /** Not-null value. */
    private String toId;
    /** Not-null value. */
    private String channleId;
    /** Not-null value. */
    private String imgUrl;
    private boolean fromMe;

    public DBMessage() {
    }

    public DBMessage(Long id) {
        this.id = id;
    }

    public DBMessage(Long id, String message, String date, String fromId, String toId, String channleId, String imgUrl, boolean fromMe) {
        this.id = id;
        this.message = message;
        this.date = date;
        this.fromId = fromId;
        this.toId = toId;
        this.channleId = channleId;
        this.imgUrl = imgUrl;
        this.fromMe = fromMe;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMessage() {
        return message;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMessage(String message) {
        this.message = message;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getFromId() {
        return fromId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /** Not-null value. */
    public String getToId() {
        return toId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToId(String toId) {
        this.toId = toId;
    }

    /** Not-null value. */
    public String getChannleId() {
        return channleId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChannleId(String channleId) {
        this.channleId = channleId;
    }

    /** Not-null value. */
    public String getImgUrl() {
        return imgUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public boolean getFromMe() {
        return fromMe;
    }

    public void setFromMe(boolean fromMe) {
        this.fromMe = fromMe;
    }

}
