package me.itangqi.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import me.itangqi.greendao.DBMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBMESSAGE".
*/
public class DBMessageDao extends AbstractDao<DBMessage, Long> {

    public static final String TABLENAME = "DBMESSAGE";

    /**
     * Properties of entity DBMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Message = new Property(1, String.class, "message", false, "MESSAGE");
        public final static Property Date = new Property(2, String.class, "date", false, "DATE");
        public final static Property FromId = new Property(3, String.class, "fromId", false, "FROM_ID");
        public final static Property ToId = new Property(4, String.class, "toId", false, "TO_ID");
        public final static Property ChannleId = new Property(5, String.class, "channleId", false, "CHANNLE_ID");
        public final static Property ImgUrl = new Property(6, String.class, "imgUrl", false, "IMG_URL");
        public final static Property FromMe = new Property(7, boolean.class, "fromMe", false, "FROM_ME");
    };


    public DBMessageDao(DaoConfig config) {
        super(config);
    }
    
    public DBMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBMESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESSAGE\" TEXT NOT NULL ," + // 1: message
                "\"DATE\" TEXT NOT NULL ," + // 2: date
                "\"FROM_ID\" TEXT NOT NULL ," + // 3: fromId
                "\"TO_ID\" TEXT NOT NULL ," + // 4: toId
                "\"CHANNLE_ID\" TEXT NOT NULL ," + // 5: channleId
                "\"IMG_URL\" TEXT NOT NULL ," + // 6: imgUrl
                "\"FROM_ME\" INTEGER NOT NULL );"); // 7: fromMe
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBMESSAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMessage());
        stmt.bindString(3, entity.getDate());
        stmt.bindString(4, entity.getFromId());
        stmt.bindString(5, entity.getToId());
        stmt.bindString(6, entity.getChannleId());
        stmt.bindString(7, entity.getImgUrl());
        stmt.bindLong(8, entity.getFromMe() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBMessage readEntity(Cursor cursor, int offset) {
        DBMessage entity = new DBMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // message
            cursor.getString(offset + 2), // date
            cursor.getString(offset + 3), // fromId
            cursor.getString(offset + 4), // toId
            cursor.getString(offset + 5), // channleId
            cursor.getString(offset + 6), // imgUrl
            cursor.getShort(offset + 7) != 0 // fromMe
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBMessage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMessage(cursor.getString(offset + 1));
        entity.setDate(cursor.getString(offset + 2));
        entity.setFromId(cursor.getString(offset + 3));
        entity.setToId(cursor.getString(offset + 4));
        entity.setChannleId(cursor.getString(offset + 5));
        entity.setImgUrl(cursor.getString(offset + 6));
        entity.setFromMe(cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBMessage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
